# Generated by Django 3.0.3 on 2021-09-14 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0003_auto_20210913_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_result',
            old_name='descripton',
            new_name='description',
        ),
    ]
