# Generated by Django 3.0.3 on 2021-09-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchApp', '0004_auto_20210915_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search_detail',
            name='schedule',
            field=models.DateTimeField(),
        ),
    ]
